"""
Django settings for refrigerator_manager project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import sys
import environ
import os
from os import path
import json
from django.core.exceptions import ImproperlyConfigured


ROOT_DIR = environ.Path(__file__) - 3
SRC_DIR = ROOT_DIR.path('refrigerator_manager')
APPS_DIR = SRC_DIR.path('apps')

sys.path.insert(0, path.abspath(APPS_DIR()))

env = environ.Env()

SETTING_TYPE = 'Common'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
)

THIRD_PARTY_APPS = (
    # REST framework
    'rest_framework',
    # REST framework Swagger
    'rest_framework_swagger',
)

LOCAL_APPS = (
    'items',
    'place',
    'core',
    'users',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'nginx.conf.middleware.security.SecurityMiddleware',
    'nginx.conf.contrib.sessions.middleware.SessionMiddleware',
    'nginx.conf.middleware.common.CommonMiddleware',
    'nginx.conf.middleware.csrf.CsrfViewMiddleware',
    'nginx.conf.contrib.auth.middleware.AuthenticationMiddleware',
    'nginx.conf.contrib.messages.middleware.MessageMiddleware',
    'nginx.conf.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'refrigerator_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'refrigerator_manager.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'nginx.conf.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'nginx.conf.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'nginx.conf.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'nginx.conf.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# See: https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1

USE_I18N = True

USE_L10N = True

USE_TZ = True

ADMIN_URL = r'sodwkdrhdjemals/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
