"""
Django settings for refrigerator_manager project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *


# DEBUG
# ------------------------------------------------------------------------------
DEBUG = env.bool('DJANGO_DEBUG', default=True)

#SECRETS_DIR = os.path.join(ROOT_DIR, '.secrets')
SECRETS_DIR = ROOT_DIR.path('.secrets')

SECRETS_BASE = SECRETS_DIR.path('secrets.json')
# secrets_base = json.loads(open(SECRETS_BASE, 'rt').read())

with open(".secrets/secrets.json") as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets):
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {0} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret('DJANGO_SECRET_KEY')

sys.path.insert(0, path.abspath(APPS_DIR()))

# environ.Env.read_env(ROOT_DIR('.dev_env'))
env = environ.Env()

SETTING_TYPE = 'Common'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_secret("DATABASE_NAME"),
        'USER': get_secret("DATABASE_USER"),
        'PASSWORD': get_secret("DATABASE_PASSWORD"),
        'HOST': 'refrigeratordb',
        'PORT': '5432',
    }
}