"""
Django settings for refrigerator_manager project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *


# DEBUG
# ------------------------------------------------------------------------------
DEBUG = env.bool('DJANGO_DEBUG', default=True)

SECRETS_DIR = os.path.join(ROOT_DIR, '.secrets')
SECRETS_BASE = os.path.join(SECRETS_DIR, 'secrets.json')
secrets_base = json.loads(open(SECRETS_BASE, 'rt').read())

SECRET_KEY = secrets_base['DJANGO_SECRET_KEY']

sys.path.insert(0, path.abspath(APPS_DIR()))

# environ.Env.read_env(ROOT_DIR('.dev_env'))
env = environ.Env()

SETTING_TYPE = 'Common'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': secrets_base['DATABASE_NAME'],
        'USER': secrets_base["DATABASE_USER"],
        'PASSWORD': secrets_base["DATABASE_PASSWORD"],
        'HOST': 'refrigeratordb',
        'PORT': '5432',
    }
}