# Generated by Django 2.0.4 on 2018-06-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LOIN', '등심'), ('TENDERLOIN', '안심'), ('BELLY', '삼겹살'), ('PICNIC', '앞다리살'), ('REG', '뒷다리살'), ('RIBS', '갈비'), ('BACKRIBS', '등갈비'), ('COLLAR', '목살')], max_length=20, null=True)),
                ('save_begin', models.DateField(auto_now_add=True)),
                ('storage_period', models.IntegerField(default=7)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gram_per_package', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'forks',
                'db_table': 'fork',
            },
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAPRIKA', '파프리카'), ('GREEN PUMPKIN', '애호박'), ('SPINACH', '시금치'), ('EGGPLANT', '가지'), ('GREEN_BEAN_SPROUTS', '숙주')], max_length=20, null=True)),
                ('save_begin', models.DateField(auto_now_add=True)),
                ('storage_period', models.IntegerField(default=7)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'vegetables',
                'db_table': 'vegetable',
            },
        ),
    ]
