# Generated by Django 2.0.4 on 2018-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAPRIKA', 'Paprika'), ('GREEN PUMPKIN', 'Green Pumpkin')], max_length=20, null=True)),
                ('save_begin', models.DateField(auto_now_add=True)),
                ('storage_period', models.IntegerField(default=7)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'vegetables',
                'db_table': 'vegetable',
            },
        ),
    ]
