# Generated by Django 2.0.4 on 2018-05-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paprika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VEGETABLE', 'Vegetable'), ('SAUCE', 'Sauce'), ('BEEF', 'Beef'), ('PORK', 'Pork'), ('NUT', 'Nut'), ('MUSHROOM', 'Mushroom'), ('FISH', 'Fish'), ('DAIRY_PRODUCT', 'Dairy product'), ('GRAIN', 'Grain'), ('INSTANT', 'Instant'), ('SIDE_DISH', 'Side dish'), ('FRUIT', 'Fruit')], default='VEGETABLE', max_length=20)),
                ('save_begin', models.DateField(auto_now_add=True)),
                ('storage_period', models.IntegerField(default=7)),
                ('quantity', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
            ],
            options={
                'verbose_name_plural': 'paprikas',
                'db_table': 'paprika',
            },
        ),
    ]
