# Generated by Django 2.0.4 on 2018-06-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
