# Generated by Django 2.0.4 on 2018-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180622_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forks',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
